resources:
  - name: pb1res
    type: PropertyBag
    configuration:
      commitSha: 1
      runID: 1
      
  - name: pb2outputRes
    type: PropertyBag
    configuration:
      test: ''
      
pipelines:

  - name: affinityGroupPipeline1
    configuration:
      affinityGroup: pipe1
      environmentVariables:
        readOnly: 
          TEST_ENV: "pipelines"
          JUST_FES: "options"
          LOL_FOO: "test"
    steps:
      - name: oneCol_step1ag
        type: Bash
        configuration:
          environmentVariables:
            key1: "value1"
            key2: "value2"
            key3: "value3"
        execution:
          onExecute:
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $key1
            - echo $key2
            - echo $key3
            - echo $step_node_name
            - echo "Running " $pipeline_name "|" $step_name > $shared_workspace/myoutput.txt
            - cat $shared_workspace/myoutput.txt
            
      - name: twoCol_step1ag
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1ag
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $step_node_name
            - echo "Running " $pipeline_name "|" $step_name > $shared_workspace/twoCol_step1ag.txt
            - cat $shared_workspace/twoCol_step1ag.txt
                       
      - name: twoCol_step2ag
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1ag
          outputResources:
            - name: pb2outputRes
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO   
            - write_output pb2outputRes test=$commitSha runID=$current_runid
            - echo $step_node_name
            - cat $shared_workspace/myoutput.txt
            
      - name: twoCol_step3ag
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1ag
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $step_node_name
            - ls $shared_workspace
            - cat $shared_workspace/myoutput.txt
                        
      - name: twoCol_step4ag
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1ag
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $step_node_name
            - ls $shared_workspace
            - cat $shared_workspace/myoutput.txt
                                    
      - name: twoCol_step5ag
        type: Bash
        configuration:
          inputSteps:
            - name: oneCol_step1ag
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - echo $step_node_name
            - ls $shared_workspace
            - cat $shared_workspace/myoutput.txt
            
  - name: affinityGroupPipeline2ag
    configuration:
      affinityGroup: pipe2 
    steps:
      - name: threeCol_step1ag
        type: Bash
        configuration:
          inputResources:
            - name: pb2outputRes
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
            - echo $step_node_name
            
      - name: threeCol_step2ag
        type: Bash
        configuration:
          inputResources:
            - name: pb2outputRes
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO
            - sleep 30s
            - echo $step_node_name
                    
      - name: threeCol_step3ag
        type: Bash
        configuration:
          inputResources:
            - name: pb2outputRes
        execution:
          onExecute:
            - printenv
            - echo $TEST_ENV
            - echo $JUST_FES
            - echo $LOL_FOO 
            - sleep 30s
                                
      - name: fourCol_step1ag
        type: Bash
        configuration:
          inputResources:
            - name: pb1res
          inputSteps:
            - name: threeCol_step1ag
            - name: threeCol_step2ag
        execution:
          onExecute:
            - printenv
            
  - name: affinityGroupPipeline4
    steps:          
      - name: fiveCol_step1ag
        type: Bash
        configuration:
          affinityGroup: stepag1
          inputResources:
            - name: pb1res
        execution:
          onExecute:
            - printenv
            
  - name: affinityGroupPipeline3  
    steps:
      - name: sixCol_step1ag
        type: Bash
        configuration:
          affinityGroup: stepag1  
          inputResources:
            - name: pb1res
        execution:
          onExecute:
            - printenv
            - echo $step_node_name
                             
      - name: sixCol_step2ag
        type: Bash
        configuration:
          affinityGroup: stepag1 
          inputSteps:
            - name: sixCol_step1ag
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo $step_node_name
      
      - name: sixCol_step3ag
        type: Bash
        configuration:
          affinityGroup: stepag1 
          inputSteps:
            - name: sixCol_step1ag
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo $step_node_name
            
      - name: sixCol_step4ag
        type: Bash
        configuration:
          affinityGroup: stepag2
          inputSteps:
            - name: sixCol_step1ag
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo $step_node_name
          
      - name: sixCol_step5ag
        type: Bash
        configuration:
          affinityGroup: stepag2
          inputSteps:
            - name: sixCol_step1ag
        execution:
          onExecute:
            - printenv
            - sleep 30s
            - echo $step_node_name
            
      - name: sevenCol_step1ag
        type: Bash
        configuration:
          affinityGroup: stepag2
          inputResources:
            - name: pb1res
          inputSteps:
            - name: sixCol_step1ag
        execution:
          onExecute:
            - printenv 
            - echo $step_node_name