resources:
  - name: WONParentSucess_resource
    type: PropertyBag
    configuration:
      test: test

  - name: WONParentSucess_resource2
    type: PropertyBag
    configuration:
      test: test
  - name: dependencyModeRepoSimpleMain
    type: GitRepo
    configuration:
      gitProvider: git_int
      path: shashank-taliwal/run_adjacency
      branches:
        include: main

pipelines:
  - name: A_waitOnParentSuccess_parentPipeline
    steps:  
      - name: A_parentStepForSuccess
        type: Bash
        configuration:
          inputResources:
            - name: dependencyModeRepoSimpleMain
          outputResources:
            - name: WONParentSucess_resource
        execution:
          onExecute:
            - sleep 2m
            - write_output WONParentSucess_resource test=${run_number}

  - name: A_waitOnParentSuccess_childPipeline
    configuration:
      dependencyMode:
        waitOnParentSuccess: true
    steps:  
      - name: A_waitOnParentSuccess
        type: Bash
        configuration:
          inputResources:
            - name: WONParentSucess_resource
        execution:
          onExecute:
            - echo ${res_WONParentSucess_resource_test}
            
            
  - name: B_waitOnParentSuccess_parentPipeline_failCase
    steps:  
      - name: B_parentStepForFailure
        type: Bash
        configuration:
          inputResources:
            - name: dependencyModeRepoSimpleMain
          outputResources:
            - name: WONParentSucess_resource2
        execution:
          onExecute:
            - write_output WONParentSucess_resource2 test=${run_number}
            - testsssDADA

  - name: B_waitOnParentSuccess_childPipeline_failCase
    configuration:
      dependencyMode:
        waitOnParentSuccess: true
    steps:  
      - name: B_waitOnParentNeverTriggered
        type: Bash
        configuration:
          inputResources:
            - name: WONParentSucess_resource2
        execution:
          onExecute:
            - echo ${res_WONParentSucess_resource2_test}