resources:
  - name: WONParentComplete_resource
    type: PropertyBag
    configuration:
      test: test

  - name: dependencyModeRepo
    type: GitRepo
    configuration:
      gitProvider: git_int
      path: shashank-taliwal/run_adjacency
      branches:
        include: main

pipelines:
  - name: A_waitOnParentComplete_parentPipeline
    steps:  
      - name: createImage
        type: Bash
        configuration:
          inputResources:
            - name: dependencyModeRepo
          outputResources:
            - name: WONParentComplete_resource
        execution:
          onExecute:
            - write_output WONParentComplete_resource test=${run_number}
            - sleep 30s
            - tdcdadad

  - name: A_waitOnParentComplete_childPipeline
    configuration:
      dependencyMode:
        waitOnParentComplete: true
    steps:  
      - name: A_waitOnParentStep
        type: Bash
        configuration:
          inputResources:
            - name: WONParentComplete_resource
        execution:
          onExecute:
            - echo ${res_WONParentComplete_resource_test}